name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-files
                  path: |
                      dist
                      package.json
                      package-lock.json

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-files
                  path: build-files

            - name: List downloaded artifact
              run: ls -la build-files

            - name: Ensure target directory exists on server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  script: |
                      mkdir -p /home/school-districts-endpoint

            - name: Copy Build Files to Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  source: 'build-files/.'
                  target: '/home/school-districts-endpoint/'
                  strip_components: 1

            - name: Install Node Modules on Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  script: |
                      cd /home/school-districts-endpoint
                      npm ci

            - name: Restart Application with PM2 on Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  script: |
                      cd /home/school-districts-endpoint
                      pm2 reload all || pm2 start dist/server.js --name united-states-school-districts
                      pm2 save

            - name: List deployment directory contents
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  script: 'ls -la /home/school-districts-endpoint/'
