name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            dist
            ecosystem.config.js
            school_district_data
            package.json
            package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build-files

      - name: List downloaded artifact
        run: ls -la build-files

      - name: Ensure target directory exists on Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /root/us-school-districts-api

      - name: Copy Build Files to Linode Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: 'build-files/.'
          target: '/root/us-school-districts-api/'
          strip_components: 1

      - name: List deployment directory contents
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: 'ls -la /root/us-school-districts-api/'

      - name: Install Node Modules and Setup Database on Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/us-school-districts-api
            npm ci
            # Rebuild better-sqlite3 for current Node version
            npm rebuild better-sqlite3 || npm install better-sqlite3

            # Ensure school_district_data directory exists
            mkdir -p school_district_data

            # Download shapefile if not present
            if [ ! -f "school_district_data/EDGE_SCHOOLDISTRICT_TL24_SY2324.shp" ]; then
              echo "Downloading NCES shapefile..."
              cd school_district_data
              # Download the shapefile from NCES (2024 school year data)
              wget -q --show-progress "https://www2.census.gov/geo/tiger/TIGER2024/SCSD/tl_2024_us_scsd.zip" -O scsd.zip
              if [ $? -eq 0 ]; then
                unzip -q scsd.zip
                # Rename to expected filename pattern
                mv tl_2024_*_scsd.shp EDGE_SCHOOLDISTRICT_TL24_SY2324.shp 2>/dev/null || true
                mv tl_2024_*_scsd.dbf EDGE_SCHOOLDISTRICT_TL24_SY2324.dbf 2>/dev/null || true
                mv tl_2024_*_scsd.shx EDGE_SCHOOLDISTRICT_TL24_SY2324.shx 2>/dev/null || true
                rm -f scsd.zip
                echo "Shapefile downloaded successfully"
              else
                echo "Failed to download shapefile, trying alternative source..."
                # Try alternative: Previous year's data
                wget -q --show-progress "https://www2.census.gov/geo/tiger/GENZ2023/shp/cb_2023_us_scsd_500k.zip" -O scsd_alt.zip
                if [ $? -eq 0 ]; then
                  unzip -q scsd_alt.zip
                  mv cb_2023_us_scsd_500k.shp EDGE_SCHOOLDISTRICT_TL24_SY2324.shp 2>/dev/null || true
                  mv cb_2023_us_scsd_500k.dbf EDGE_SCHOOLDISTRICT_TL24_SY2324.dbf 2>/dev/null || true
                  mv cb_2023_us_scsd_500k.shx EDGE_SCHOOLDISTRICT_TL24_SY2324.shx 2>/dev/null || true
                  rm -f scsd_alt.zip
                  echo "Alternative shapefile downloaded successfully"
                else
                  echo "ERROR: Could not download shapefile from any source"
                  exit 1
                fi
              fi
              cd ..
            fi

            # Ensure database exists
            if [ ! -f "school_district_data/districts.db" ]; then
              echo "Database not found, creating from shapefile..."
              npm run setup-db
            fi

            # Verify database exists and is valid
            if [ -f "school_district_data/districts.db" ]; then
              DB_SIZE=$(stat -c%s "school_district_data/districts.db" 2>/dev/null)
              if [ -n "$DB_SIZE" ] && [ "$DB_SIZE" -gt 100000000 ]; then
                echo "Database verified ($(($DB_SIZE / 1024 / 1024))MB)"
              else
                echo "Database seems invalid, recreating..."
                rm -f school_district_data/districts.db
                npm run setup-db
              fi
            else
              echo "Failed to create database!"
              exit 1
            fi

      - name: Start or Reload and Save PM2 Process on Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/us-school-districts-api
            pm2 startOrReload ecosystem.config.js
            pm2 save
