name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-files
                  path: |
                      dist
                      ecosystem.config.js
                      package.json
                      package-lock.json

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-files
                  path: build-files

            - name: List downloaded artifact
              run: ls -la build-files

            - name: Ensure target directory exists on Linode
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.LINODE_HOST }}
                  username: ${{ secrets.LINODE_USER }}
                  key: ${{ secrets.LINODE_SSH_KEY }}
                  script: |
                      mkdir -p /home/puppeteer-user/us-school-districts

            - name: Copy Build Files to Linode Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.LINODE_HOST }}
                  username: ${{ secrets.LINODE_USER }}
                  key: ${{ secrets.LINODE_SSH_KEY }}
                  source: 'build-files/.'
                  target: '/home/puppeteer-user/us-school-districts/'
                  strip_components: 1

            - name: List deployment directory contents
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.LINODE_HOST }}
                  username: ${{ secrets.LINODE_USER }}
                  key: ${{ secrets.LINODE_SSH_KEY }}
                  script: 'ls -la /home/puppeteer-user/us-school-districts/'

            - name: Install Node Modules on Linode
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.LINODE_HOST }}
                  username: ${{ secrets.LINODE_USER }}
                  key: ${{ secrets.LINODE_SSH_KEY }}
                  script: |
                      cd /home/puppeteer-user/us-school-districts
                      npm ci

            - name: Start or Reload and Save PM2 Process on Linode
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.LINODE_HOST }}
                  username: ${{ secrets.LINODE_USER }}
                  key: ${{ secrets.LINODE_SSH_KEY }}
                  script: |
                      cd /home/puppeteer-user/us-school-districts
                      pm2 startOrReload ecosystem.config.js
                      pm2 save
